export const ADMIN_ROUTE ='/admin'
export const LOGIN_ROUTE ='/login'
export const REGISTRATION_ROUTE ='/registration'
export const MENU_ROUTE ='/menu'
export const JOURNAL_ROUTE='/journals'
export const REPORT_ROUTE='/reports'
export const PRIBORY_FORM_ROUTE= '/priboryForm'
export const API_URL='/api'